### ISSUE TITLE
What is the no-sort option?

### ISSUE THREAD

**Issue by cangoektas** [azz/monorepo-experiments#1]
Hey @azz, I just stumbled upon this repo via a Google search.

I'm working on something similar and this approach seems to work really well so far. One thing I didn't get is the `no-sort` option for the watch command. I couldn't find anything about that in the lerna docs and also no reference in the lerna source code. I noticed that the watch script doesn't work without it. Could you share what it does and maybe share references where I can read more about it?

Thakns a lot!

**Comment by azz** [comment]
I think that option has since been removed from lerna, it used to run the tasks in an arbitrary order, rather than building up a tree of dependencies and building the dependencies before the dependents.

**Comment by azz** [comment]
https://github.com/lerna/lerna/pull/412/files#diff-9b8c24fea82f83af89d4f3da78c509bc

**Comment by cangoektas** [comment]
Oh, I see. Thanks a lot. Yeah, unfortunately, I had a couple of problems with the watch mode. I think dependents don't compile when using the `no-sort` option. My guess is that lerna is waiting for the dependencies to finish but since that's not happening in watch mode it waits forever.

As a workaround, I found that just having a single `rollup.config.js` that exports configs for every single package seems to work better. It's crazy how much hustle it was just to get this to work. Thanks for this repo, it definitely was a good starting point. 👍
